"""Add dynamic table support

Revision ID: 1d97ff5a107f
Revises: 2a7b8c9d0e1f
Create Date: 2026-02-03 14:31:03.245468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d97ff5a107f'
down_revision: Union[str, None] = '2a7b8c9d0e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('column_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_summable', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('unit_kerja_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_kerja_id'], ['unit_kerja.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_index('ix_arsip_summary_instansi_id', table_name='arsip_summary')
    # op.drop_index('ix_arsip_summary_jenis_arsip', table_name='arsip_summary')
    # op.drop_index('ix_arsip_summary_role_id', table_name='arsip_summary')
    # op.drop_index('ix_arsip_summary_tanggal', table_name='arsip_summary')
    # op.drop_table('arsip_summary')
    # op.drop_index('ix_daily_summary_tanggal', table_name='daily_summary')
    # op.drop_index('tanggal', table_name='daily_summary')
    # op.drop_table('daily_summary')
    # op.drop_index('ix_arsip_data_instansi_id', table_name='arsip_data')
    # op.drop_index('ix_arsip_data_role_id', table_name='arsip_data')
    # op.drop_index('ix_arsip_data_tanggal', table_name='arsip_data')
    # op.drop_table('arsip_data')
    # op.alter_column('data_arsip', 'created_at',
    #            existing_type=mysql.DATETIME(),
    #            server_default=None,
    #            existing_nullable=True)
    # op.alter_column('data_arsip', 'updated_at',
    #            existing_type=mysql.DATETIME(),
    #            server_default=None,
    #            existing_nullable=True)
    # op.drop_index('ix_data_arsip_tanggal', table_name='data_arsip')
    # op.drop_index('ix_data_arsip_unit_kerja_id', table_name='data_arsip')
    # op.alter_column('instansi', 'created_at',
    #            existing_type=mysql.DATETIME(),
    #            server_default=None,
    #            existing_nullable=True)
    # op.alter_column('instansi', 'updated_at',
    #            existing_type=mysql.DATETIME(),
    #            server_default=None,
    #            existing_nullable=True)
    # op.drop_index('ix_instansi_kode', table_name='instansi')
    # op.drop_index('ix_instansi_nama', table_name='instansi')
    # op.alter_column('unit_kerja', 'created_at',
    #            existing_type=mysql.DATETIME(),
    #            server_default=None,
    #            existing_nullable=True)
    # op.alter_column('unit_kerja', 'updated_at',
    #            existing_type=mysql.DATETIME(),
    #            server_default=None,
    #            existing_nullable=True)
    # op.drop_index('ix_unit_kerja_instansi_id', table_name='unit_kerja')
    # op.drop_index('ix_unit_kerja_kode', table_name='unit_kerja')
    # op.drop_index('ix_unit_kerja_nama', table_name='unit_kerja')
    # op.alter_column('users', 'created_at',
    #            existing_type=mysql.DATETIME(),
    #            server_default=sa.text('now()'),
    #            existing_nullable=True)
    # op.drop_index('username', table_name='users')
    # op.drop_index('ix_users_username', table_name='users')
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('username', 'users', ['username'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.create_index('ix_unit_kerja_nama', 'unit_kerja', ['nama'], unique=False)
    op.create_index('ix_unit_kerja_kode', 'unit_kerja', ['kode'], unique=False)
    op.create_index('ix_unit_kerja_instansi_id', 'unit_kerja', ['instansi_id'], unique=False)
    op.alter_column('unit_kerja', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('unit_kerja', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.create_index('ix_instansi_nama', 'instansi', ['nama'], unique=False)
    op.create_index('ix_instansi_kode', 'instansi', ['kode'], unique=False)
    op.alter_column('instansi', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('instansi', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.create_index('ix_data_arsip_unit_kerja_id', 'data_arsip', ['unit_kerja_id'], unique=False)
    op.create_index('ix_data_arsip_tanggal', 'data_arsip', ['tanggal'], unique=False)
    op.alter_column('data_arsip', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('data_arsip', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.create_table('arsip_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DATE(), nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('jenis_arsip', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('instansi_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('data_content', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('keterangan', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_arsip_data_tanggal', 'arsip_data', ['tanggal'], unique=False)
    op.create_index('ix_arsip_data_role_id', 'arsip_data', ['role_id'], unique=False)
    op.create_index('ix_arsip_data_instansi_id', 'arsip_data', ['instansi_id'], unique=False)
    op.create_table('daily_summary',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DATE(), nullable=False),
    sa.Column('total_arsip', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_instansi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_jenis', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('tanggal', 'daily_summary', ['tanggal'], unique=True)
    op.create_index('ix_daily_summary_tanggal', 'daily_summary', ['tanggal'], unique=False)
    op.create_table('arsip_summary',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DATE(), nullable=False),
    sa.Column('instansi_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('jenis_arsip', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_arsip_summary_tanggal', 'arsip_summary', ['tanggal'], unique=False)
    op.create_index('ix_arsip_summary_role_id', 'arsip_summary', ['role_id'], unique=False)
    op.create_index('ix_arsip_summary_jenis_arsip', 'arsip_summary', ['jenis_arsip'], unique=False)
    op.create_index('ix_arsip_summary_instansi_id', 'arsip_summary', ['instansi_id'], unique=False)
    op.drop_table('dynamic_data')
    op.drop_table('column_definitions')
    op.drop_table('table_definitions')
    # ### end Alembic commands ###
